### ISSUE TITLE
modularize analysis sequence 

### ISSUE THREAD

**Issue by cbernet** [cbernet/cmgtools-lite#29]
We could think of modularizing more: 
e.g. 

* TauAnalyzer
    * evaluate tau ID but do not select 
    * possibly tau E correction
* Selector (for taus)
    * generic selector module (based on function object provided in cfg)
* MuAnalyzer  
* ElectronAnalyzer
* Selector (signal muons)
* Selector (di-muon veto)
* Selector (third-lepton veto)
* DiLeptonAnalyzer
* DiMuonVeto (flags event or creates a collection with the selected muon pair) 
* ThirdLeptonVeto (flags event or creates a collection with extra leptons)
* Selector (for di-leptons)
* JetAnalyzer 
    * jet energy corrections
* Selector (for jets)
* Selector (select b jets)
* BJetSFAnalyzer
    * promote / demote
* TreeProducer 
    * one TreeProducer class per channel, no common base class, make use of functions in a common module (e.g. book_tau, book_e)

**Comment by GaelTouquet** [comment]
Should be closed?
