### ISSUE TITLE
export X509_USER_PROXY conflict with xrdcp

### ISSUE THREAD

**Issue by lucastorterotot** [cbernet/cmgtools-lite#61]
When trying to do the following command
```bash 
xrdcp root://cms-xrd-global.cern.ch//store/user/jbechtel/gc_storage/TauTau_data_2017_CMSSW944/TauEmbedding_TauTau_data_2017_CMSSW944_Run2017B/37/merged_336.root_ .
```
I get
```bash 
Run: [ERROR] Server responded with an error: [3011] No servers are available to read the file.
```
but it works when I comment [this line](https://github.com/cbernet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/init.sh#L12) which has been added on june 18th in the commit `db1e7e1b8` (_added initialization script_).

Is this line required?

Along with @GaelTouquet we found this conflict while trying to run Heppy on embedded samples.

**Comment by cbernet** [comment]
If it works for both of you without the line, can you send a PR for the fix? I actually don't know what this line is doing :-)
